# Generated by Django 6.0.5 on 2026-05-08 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episode', models.IntegerField()),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField()),
                ('keywords', models.TextField(help_text='space-separated keywords for search')),
                ('tags', models.TextField(help_text='comma-separated tags (naruto, sasuke, fight...)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenes', to='core.anime')),
            ],
        ),
    ]
